### ISSUE TITLE
Push source code?

### ISSUE THREAD

**Issue by sim1cent** [ZenoArrows/The-Simpsons-Hit-and-Run#34]
It looks like the modifications in order to build for the switch aren't available since the only thing changed is the README (maybe i'm doing something wrong).
I'm asking because i would like to do a linux port for fun and starting from a switch base might help me.

**Comment by sim1cent** [comment]
Even if it's incomplete you might want to push it, it will speed up development

**Comment by ZenoArrows** [comment]
It should already compile for Linux, but it doesn't include any of the keyboard/mouse support and in general I assumed people would prefer to run it through proton since that gives you access to mods.

I do plan to release the source code soon, I'm currently working on preparations for that, however I'm a bit worried about stability. The port is pretty unstable right now with some very hard to debug issues and taking in pull requests at this point might exacerbate the stability issues.

**Comment by sim1cent** [comment]
Makes sense, thanks for answering.

**Comment by ZenoArrows** [comment]
I've pushed the source code, you should be able to compile it now using CMake

**Comment by sim1cent** [comment]
That's nice, thanks!
